#!/usr/bin/env bash

# Exit if anything fails
set -eo pipefail

# Utilities
GREEN="\033[00;32m"
YELLOW="\033[00;33m"

function log () {
  echo -e "$1"
  echo "################################################################################"
  echo "#### $2 "
  echo "################################################################################"
  echo -e "\033[0m"
}

# Source of the runnable examples. Defaults to the `lib/examples` git submodule.
# Override with: EXAMPLES_DIR=/path/to/examples ./scripts/update.sh
EXAMPLES_DIR="${EXAMPLES_DIR:-lib/examples}"
# GitHub repository the examples live in (used for source links).
EXAMPLES_REPO="${EXAMPLES_REPO:-https://github.com/throgxyz/examples}"
# Set SKIP_SUBMODULE=1 to skip syncing the submodule (e.g. when offline).
SKIP_SUBMODULE="${SKIP_SUBMODULE:-0}"

# Runnable example sources, copied here and embedded into pages.
SNIPPETS_PATH="./vocs/docs/snippets"
# Generated example pages.
MDX_SNIPPETS_PATH="./vocs/docs/pages/examples"
# Hand-written per-category templates (edit these, not the generated pages).
MDX_TEMPLATES_PATH="./vocs/docs/pages/templates"
# Generated sidebar items.
SIDEBAR_ITEMS_PATH="./vocs/example-items.ts"

# This script will do the following:
#
# 1. Copy the example sources from $EXAMPLES_DIR into the snippets directory.
# 2. Generate a markdown page for each example, embedding the source by
#    reference and linking back to GitHub.
# 3. Generate one category landing page per template.
# 4. Generate the sidebar items TS file from the templates.
function main () {
  log "$GREEN" "Updating..."

  # Change directory to project root
  SCRIPT_PATH="$( cd "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
  cd "$SCRIPT_PATH/.." || exit

  # Sync the examples submodule to the latest `main` (unless disabled or using
  # a custom EXAMPLES_DIR).
  if [ "$SKIP_SUBMODULE" != "1" ] && [ "$EXAMPLES_DIR" = "lib/examples" ] && [ -f .gitmodules ]; then
    echo "Syncing $EXAMPLES_DIR submodule..."
    git submodule update --init --remote lib/examples || \
      echo "warning: could not sync submodule (offline?); using current checkout."
  fi

  if [ ! -d "$EXAMPLES_DIR/examples" ]; then
    echo "error: '$EXAMPLES_DIR/examples' not found." >&2
    echo "       Run 'git submodule update --init', or set EXAMPLES_DIR." >&2
    exit 1
  fi

  # Create the $SNIPPETS_PATH directory if it doesn't exist
  mkdir -p "$SNIPPETS_PATH"

  # Create the $MDX_SNIPPETS_PATH directory if it doesn't exist
  mkdir -p "$MDX_SNIPPETS_PATH"

  # Refresh the example sources (drop categories that no longer exist).
  echo "Copying examples to $SNIPPETS_PATH"
  for CATEGORY_DIR in "$EXAMPLES_DIR"/examples/*/; do
    CATEGORY=$(basename "$CATEGORY_DIR")
    rm -rf "${SNIPPETS_PATH:?}/$CATEGORY"
    mkdir -p "$SNIPPETS_PATH/$CATEGORY/examples"
    cp "$CATEGORY_DIR"examples/*.rs "$SNIPPETS_PATH/$CATEGORY/examples/" 2>/dev/null || true
  done

  log "$GREEN" "Copied examples to $SNIPPETS_PATH"

  # Get the commit hash of the latest commit in the examples repository
  EXAMPLES_COMMIT_HASH=$(git -C "$EXAMPLES_DIR" rev-parse HEAD 2>/dev/null || echo "main")

  # Clean up existing generated example pages
  echo "Cleaning up existing example pages"
  rm -rf "${MDX_SNIPPETS_PATH:?}"/*
  mkdir -p "$MDX_SNIPPETS_PATH"

  # Create example markdown files
  for CODE_DIRPATH in "$EXAMPLES_DIR"/examples/*/; do
    # Get the example category directory name
    EXAMPLE_DIRNAME=$(basename "$CODE_DIRPATH")

    # Skip categories without a hand-written template
    MDX_TEMPLATE_FILEPATH="$MDX_TEMPLATES_PATH/$EXAMPLE_DIRNAME/README.mdx"
    if [ ! -f "$MDX_TEMPLATE_FILEPATH" ]; then
      echo "Skipping '$EXAMPLE_DIRNAME' (no template at $MDX_TEMPLATE_FILEPATH)"
      continue
    fi

    # Populate the generated pages directory with the category directory
    mkdir -p "$MDX_SNIPPETS_PATH/$EXAMPLE_DIRNAME"

    # Category landing page = the template content
    EXAMPLE_README_MDX="$MDX_SNIPPETS_PATH/$EXAMPLE_DIRNAME/README.mdx"
    printf "%s\n\n%s\n" \
      "import Template from '../../templates/$EXAMPLE_DIRNAME/README.mdx'" \
      "<Template />" > "$EXAMPLE_README_MDX"
    echo "Creating $EXAMPLE_README_MDX"

    # One page per example file
    for EXAMPLE_FILEPATH in "$CODE_DIRPATH"examples/*.rs; do
      [ -f "$EXAMPLE_FILEPATH" ] || continue
      EXAMPLE_FILENAME=$(basename "$EXAMPLE_FILEPATH" .rs)
      MDX_SNIPPET="$MDX_SNIPPETS_PATH/$EXAMPLE_DIRNAME/$EXAMPLE_FILENAME.mdx"

      echo "Creating $MDX_SNIPPET"

cat << EOF > "$MDX_SNIPPET"
{/*DO NOT EDIT THIS FILE. IT IS GENERATED BY RUNNING \`./scripts/update.sh\`
ANY CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN
EDIT OR CREATE THIS TEMPLATE INSTEAD: $MDX_TEMPLATE_FILEPATH
LATEST UPDATE: $EXAMPLES_REPO/tree/$EXAMPLES_COMMIT_HASH
*/}

## Example: \`$EXAMPLE_FILENAME\`

To run this example:

- Clone the [examples]($EXAMPLES_REPO) repository: \`git clone $EXAMPLES_REPO.git\`
- Run: \`cargo run -p examples-$EXAMPLE_DIRNAME --example $EXAMPLE_FILENAME\`

\`\`\`rust
// [!include ~/snippets/$EXAMPLE_DIRNAME/examples/$(basename "$EXAMPLE_FILEPATH")]
\`\`\`

Find the source code on GitHub [here]($EXAMPLES_REPO/tree/$EXAMPLES_COMMIT_HASH/examples/$EXAMPLE_DIRNAME/examples/$EXAMPLE_FILENAME.rs).
EOF
    done
  done

  # Generate sidebar items TS file
  echo "Generating sidebar items at $SIDEBAR_ITEMS_PATH"

  # Header of the TS file
  cat << 'EOF' > "$SIDEBAR_ITEMS_PATH"
// DO NOT EDIT THIS FILE. ANY CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN.
// Generated by ./scripts/update.sh

import type { SidebarItem } from "./types";

export const exampleItems: SidebarItem[] = [
EOF

  # For each template directory (category)
  for TEMPLATE_DIR in "$MDX_TEMPLATES_PATH"/*/; do
    [ -d "$TEMPLATE_DIR" ] || continue
    EXAMPLE_DIRNAME=$(basename "$TEMPLATE_DIR")
    README_FILE="$TEMPLATE_DIR/README.mdx"

    # Skip if there's no README template yet
    [ -f "$README_FILE" ] || continue

    # Generate section label from the first `## ` heading
    SECTION_LABEL=$(grep -m1 '^## ' "$README_FILE" | sed 's/^##[[:space:]]*//')

    # Start section block
    printf "    { text: '%s', collapsed: true, link: '/examples/%s/README', items: [\n" \
      "$SECTION_LABEL" "$EXAMPLE_DIRNAME" >> "$SIDEBAR_ITEMS_PATH"

    # Parse bullet list lines: - [Title](/examples/.../file)
    while IFS= read -r line; do
      if [[ "$line" == "- ["* ]]; then
        trimmed="${line#- }"
        title_part="${trimmed#\[}"
        TEXT="${title_part%%]*}"
        link_part="${trimmed#*](/}"
        LINK="/${link_part%%)*}"
        ESCAPED_TEXT=${TEXT//\'/\\\'}
        printf "        { text: '%s', link: '%s' },\n" \
          "$ESCAPED_TEXT" "$LINK" >> "$SIDEBAR_ITEMS_PATH"
      fi
    done < <(cat "$README_FILE"; echo)

    # Close section block
    echo "    ]}," >> "$SIDEBAR_ITEMS_PATH"
  done

  # Footer of the TS file
  echo "]" >> "$SIDEBAR_ITEMS_PATH"

  log "$YELLOW" "Edit \`./vocs/docs/pages/templates/*/README.mdx\` to change descriptions or ordering."

  log "$GREEN" "Done"
}

# Run the main function
# This prevents partial execution in case of incomplete downloads
main
