// DO NOT EDIT THIS FILE. ANY CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN.
// Generated by ./scripts/update.sh

import type { SidebarItem } from "./types";

export const exampleItems: SidebarItem[] = [
    { text: 'Accounts', collapsed: true, link: '/examples/accounts/README', items: [
        { text: 'Create an account on-chain', link: '/examples/accounts/account_create' },
        { text: 'Set an account name', link: '/examples/accounts/account_update' },
        { text: 'Update account permissions (multi-sig)', link: '/examples/accounts/account_permissions' },
    ]},
    { text: 'Contracts', collapsed: true, link: '/examples/contracts/README', items: [
        { text: 'Read-only contract call', link: '/examples/contracts/contract_call' },
        { text: 'State-changing contract call', link: '/examples/contracts/contract_send' },
        { text: 'Deploy a contract', link: '/examples/contracts/contract_deploy' },
        { text: 'Call a contract via JSON ABI', link: '/examples/contracts/contract_dynamic_abi' },
        { text: 'Estimate energy cost', link: '/examples/contracts/contract_estimate_energy' },
        { text: 'Handle revert errors', link: '/examples/contracts/contract_revert' },
        { text: 'Decode an event log', link: '/examples/contracts/decode_log' },
        { text: 'Decode a transaction receipt', link: '/examples/contracts/decode_receipt' },
    ]},
    { text: 'Queries', collapsed: true, link: '/examples/queries/README', items: [
        { text: 'Query chain state', link: '/examples/queries/query' },
        { text: 'Address format conversions', link: '/examples/queries/address_formats' },
        { text: 'TRX amount math', link: '/examples/queries/amount_math' },
        { text: 'Connect to a custom endpoint', link: '/examples/queries/connect_custom' },
        { text: 'List witnesses (SRs)', link: '/examples/queries/list_witnesses' },
        { text: 'List governance proposals', link: '/examples/queries/governance_list' },
    ]},
    { text: 'Signers', collapsed: true, link: '/examples/signers/README', items: [
        { text: 'Generate a random keypair', link: '/examples/signers/signer_generate' },
        { text: 'Sign and verify a hash', link: '/examples/signers/signer_local' },
        { text: 'Derive from a BIP-39 mnemonic', link: '/examples/signers/signer_mnemonic' },
        { text: 'Encrypt and decrypt a keystore', link: '/examples/signers/signer_keystore' },
    ]},
    { text: 'Staking', collapsed: true, link: '/examples/staking/README', items: [
        { text: 'Stake 2.0: freeze, delegate, claim', link: '/examples/staking/stake' },
        { text: 'Stake 1.0 (legacy): freeze and unfreeze', link: '/examples/staking/stake_v1' },
        { text: 'Freeze for bandwidth', link: '/examples/staking/stake_bandwidth' },
        { text: 'Delegate resource', link: '/examples/staking/delegate' },
        { text: 'Undelegate resource', link: '/examples/staking/undelegate' },
        { text: 'Unfreeze (V2)', link: '/examples/staking/unfreeze' },
        { text: 'Cancel a pending unfreeze', link: '/examples/staking/cancel_unfreeze' },
        { text: 'Withdraw an expired unfreeze', link: '/examples/staking/withdraw_unfreeze' },
        { text: 'Claim block/vote rewards', link: '/examples/staking/claim_rewards' },
        { text: 'Vote for a witness', link: '/examples/staking/vote_witness' },
    ]},
    { text: 'Transfers', collapsed: true, link: '/examples/transfers/README', items: [
        { text: 'Send TRX', link: '/examples/transfers/transfer_trx' },
        { text: 'Send TRX with a memo', link: '/examples/transfers/transfer_trx_memo' },
    ]},
    { text: 'TRC10', collapsed: true, link: '/examples/trc10/README', items: [
        { text: 'Query token metadata by ID', link: '/examples/trc10/trc10_query' },
        { text: 'Query token metadata by name', link: '/examples/trc10/trc10_by_name' },
        { text: 'Check a TRC10 balance', link: '/examples/trc10/trc10_balance' },
        { text: 'Transfer TRC10 tokens', link: '/examples/trc10/trc10_transfer' },
        { text: 'Issue a new TRC10 token', link: '/examples/trc10/trc10_issue' },
    ]},
    { text: 'TRC20', collapsed: true, link: '/examples/trc20/README', items: [
        { text: 'Balance and transfer', link: '/examples/trc20/trc20' },
        { text: 'Approve and allowance', link: '/examples/trc20/trc20_approve' },
        { text: 'transferFrom flow', link: '/examples/trc20/trc20_transfer_from' },
        { text: 'Decode Transfer events', link: '/examples/trc20/trc20_decode_transfer_event' },
    ]},
]
